### ISSUE TITLE
[BUG] Actor render sfx playing on world load (Cortex Prime System)

### ISSUE THREAD

**Issue by Moongoyzer** [SalieriC/immersive-render#5] opened 2022-10-06 22:12 UTC
After loading into the game for the first time, any first interaction with interface is followed by the opening sound at max volume. Happens only with GM account.

**To Reproduce**
1. Assign opening sound to a foulder which contains actors with different permission levels.
2. Save and log out.
3. Log in.
4. Click on any button. Sound will be played at max volume.

**Expected behavior**
I guess it happens due to diffent permission settings since players don't have this problem. I would even have been okay with this and not write this report if not for the volume of a sound.

**Desktop:**
 - OS: Windows 10
 - Foundry App
 - FVTT Version: 9.269
 - System Name and Version: Cortex Prime 0.1.0
 - IR Version:  1.1.0
 - Other Modules enabled:  FXMaster, GM Screen, libWrapper, OneJournal, Permission Viewer, Playlist Enhancer, Token Magic FX

**Comment by SalieriC** [comment] 2022-10-06 22:28
I cannot reproduce this on the SWADE system and haven't noticed it on the other supported systems, gotta check them though.
The only explanation I have for this behavious is that the Cortex Prime system calls any hooks on world load that are recognised by IR for some reason. It also seems that there are quite a few newer versions of the Cortex Prime version available. I'd suggest you try updating to the most recent version and try again. If the issue persists we might have to contact its author about it.

**Comment by Moongoyzer** [comment] 2022-10-06 22:34
Yeah, I didn't update my system because of some compatibility issues in the past. Gonna create a new test game with an updated version, will report to you if anything changes.

**Comment by SalieriC** [comment] 2022-10-06 22:35
Make a backup of the system first to fall back to in case something breaks.

**Comment by Moongoyzer** [comment] 2022-10-06 22:45
Checked it. No issues were found in a new test game with the same modules as in the old main one. I guess there are some code shenanigans which happened with it, not with the system at whole. Or I identified the issue incorrectly.

**Comment by SalieriC** [comment] 2022-10-06 22:47
Okay great. I hope nothing breaks and you can run this systems version on your main world without issues. I will close this issue but please feel free to reopen it should the error persist. Thanks for using IR. =)

**Closed as completed by SalieriC** 2022-10-06 22:47 UTC
Labels: bug, question, system

**Comment by Moongoyzer** [comment] 2022-10-06 22:51
Thanks for answering! And for the module ^^
